twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        version: '%version%'
        brand: '%brand%'
        brand_html: '%brand_html%'

when@test:
    twig:
        strict_variables: true
