controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_stimulus:
    path: /stimulus
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
        template: stimulus.html.twig